Updating create-component
groselha/create-component pull request #1
Opened 2019-01-23 10:02 UTC by silviopaganini

2019-01-24 10:25 UTC, peduarte requested changes

2019-01-24 10:25 UTC, peduarte commented on README.md
> +```
`npx` please 😂

2019-01-24 10:25 UTC, peduarte commented on template/Component.test.enzyme.js
> +import Adapter from 'enzyme-adapter-react-16'
missing `;` at the end lol

2019-01-24 10:25 UTC, peduarte commented
@silviopaganini <3

2019-02-06 14:36 UTC, silviopaganini commented
updated the PR, we don't need the Adapter as long as it's on the setupJest.js

2019-04-16 18:58 UTC, lucasmotta approved these changes

2019-04-16 18:59 UTC, merged